kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
  - |
    apiVersion: kubeadm.k8s.io/v1beta2
    kind: ClusterConfiguration
    metadata:
      name: config
    networking:
      podSubnet: "10.4.0.0/14"
      serviceSubnet: "100.4.0.0/16"
      dnsDomain: "cluster1.local"
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 80
        listenAddress: "127.0.0.1"
  - role: worker
  - role: worker
  - role: worker